---
title: "Proposal"
author: "Lauren Cunild"
date: "11/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading tidyverse
library(tidyverse)
```
## Data Sets
We want to use the mask use and rolling average data sets from the New York Times Covid-19 data repository on GitHub to analyse the relationship between the percentage of people who wear a mask, and how many Covid cases or deaths there are in that county. 
### Import data sets
```{r}
mask_use <- read.csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/mask-use/mask-use-by-county.csv')
mask_use
```
```{r}
rolling_avg <- read.csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/rolling-averages/us-counties-2021.csv')
rolling_avg
```
### Tidying and merging data sets
```{r}
rolling_avg_new <- mutate(rolling_avg,
                     geoid = as.integer(substr(geoid,5,9)))
rolling_avg_new <- rename(rolling_avg_new, COUNTYFP = geoid)
```

```{r}
data <- inner_join(rolling_avg_new, mask_use, by="COUNTYFP")
data
```
